/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelAlfombra(props) {
  const { nodes, materials } = useGLTF('Sala/alfombra.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube011.geometry} material={materials.Alfombra} position={[-1.2, 0, -0.48]} scale={[3.53, 0.03, 3.97]} />
    </group>
  )
}

useGLTF.preload('Sala/alfombra.gltf')
