/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelAparadorSala(props) {
  const { nodes, materials } = useGLTF('Sala/aparador.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gypsum.geometry} material={materials.Madera3} position={[-1.59, 1.83, -4.93]} />
    </group>
  )
}

useGLTF.preload('Sala/aparador.gltf')
