/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelBarredera(props) {
  const { nodes, materials } = useGLTF('Sala/barrederas.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.marcos_pared_y_puerta.geometry} material={materials.Door_1_PBR} position={[4.14, 1.01, -5]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('Sala/barrederas.gltf')
