/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelCeiling(props) {
  const { nodes, materials } = useGLTF('Sala/ceiling.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.negro} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Line003.geometry} material={materials.techo} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.negro} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.__001.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Line221.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Line222.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle002.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle001.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle003.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle004.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle005.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle006.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle007.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle008.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle010.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle011.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle009.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle013.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle012.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle014.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle015.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle016.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Circle001.geometry} material={materials.negro} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle018.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle019.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle023.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle024.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle025.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle026.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle027.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle030.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle028.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle032.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle029.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle031.geometry} material={materials.cadena} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.__.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.__001__2_.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.__002.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.__003.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.__004.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.__005.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.__010.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Circle002.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Star001.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Circle003.geometry} material={materials.negro} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Cylinder004__2_.geometry} material={materials.negro} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Line004.geometry} material={materials.negro} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.__012.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Line002.geometry} material={materials.foco} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.cobre} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Line158.geometry} material={materials.filamentos_2} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Box14.geometry} material={materials.pistil} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Helix33.geometry} material={materials.filamentos_2} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Line160.geometry} material={materials.filamentos_2} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Line159.geometry} material={materials.filamentos_2} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Line157.geometry} material={materials.filamentos_2} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle018__2_.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle033.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle034.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle035.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle036.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle037.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle038.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle039.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle040.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle044.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle045.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle046.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle047.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle048.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle049.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle050.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle052.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle053.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle054.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle055.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle056.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle057.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle058.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle059.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle060.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle061.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle062.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle064.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle065.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle066.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle067.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle068.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle069.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle070.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle071.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle072.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle073.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle074.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle075.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle076.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle077.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle078.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle079.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle080.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle081.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle082.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle083.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle084.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle085.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle086.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle087.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle088.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle089.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle090.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle091.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Rectangle092.geometry} material={materials.Filamentos} position={[-3.2, 1.68, -2.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
    </group>
  )
}

useGLTF.preload('Sala/ceiling.gltf')
