/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelCello(props) {
  const { nodes, materials } = useGLTF('Sala/cello.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cello.geometry} material={materials.cello_mat001} position={[3.53, 0, 4.01]} rotation={[1.73, -0.31, 2.06]} scale={1.97} />
      <mesh geometry={nodes.cello003.geometry} material={materials.cello_mat} position={[3.53, 0, 4.01]} rotation={[1.73, -0.31, 2.06]} />
      <mesh geometry={nodes.Base.geometry} material={materials.lambert1} position={[4.06, 0.01, 4.21]} scale={[0.21, 0.02, 0.21]} />
    </group>
  )
}

useGLTF.preload('Sala/cello.gltf')
