/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelCojines(props) {
  const { nodes, materials } = useGLTF('Sala/cojines.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube005.geometry} material={materials.Material} position={[-3.53, 1.36, 2.11]} rotation={[0, 0, -1.03]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Material} position={[-3.35, 1.5, -3.49]} rotation={[-1.71, -0.16, -2.39]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Material} position={[-1.3, 1.42, -3.89]} rotation={[-1.78, -0.01, 3.09]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.Material} position={[-3.53, 1.36, -0.59]} rotation={[0, 0, -1.03]} />
    </group>
  )
}

useGLTF.preload('Sala/cojines.gltf')
