/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelCortinaSalaB(props) {
  const { nodes, materials } = useGLTF('Sala/cortinasalab.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curtain_FBX2.geometry} material={materials.Material} position={[-4.9, -0.09, -0.24]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
    </group>
  )
}

useGLTF.preload('Sala/cortinasalab.gltf')
