/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelCuadroSala(props) {
  const { nodes, materials } = useGLTF('Sala/cuadro.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.Cuadro} position={[-1.52, 3.57, -4.81]} rotation={[Math.PI / 2, 0, 0]} scale={1.11} />
    </group>
  )
}

useGLTF.preload('Sala/cuadro.gltf')
