/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelEstatua(props) {
  const { nodes, materials } = useGLTF('Sala/estatua.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Estatua.geometry} material={materials.Concreto} position={[0, 0.81, 0]} scale={0.02} />
    </group>
  )
}

useGLTF.preload('Sala/estatua.gltf')
