/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelFlorero(props) {
  const { nodes, materials } = useGLTF('Sala/florero.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder002_Cylinder002.geometry} material={materials.barrederas} position={[4.57, -0.09, -4.37]} rotation={[Math.PI / 2, 0, -2.95]} scale={0} />
      <mesh geometry={nodes.Cylinder006_Cylinder001.geometry} material={materials.Tierra} position={[4.57, -0.09, -4.37]} rotation={[Math.PI / 2, 0, -2.95]} scale={0} />
      <mesh geometry={nodes.leaves001_leaves001.geometry} material={materials.Hojas} position={[4.57, -0.09, -4.37]} rotation={[Math.PI / 2, 0, -2.95]} scale={0} />
      <mesh geometry={nodes.tree003_CUtree001.geometry} material={materials.Tallos} position={[4.57, -0.09, -4.37]} rotation={[Math.PI / 2, 0, -2.95]} scale={0} />
    </group>
  )
}

useGLTF.preload('Sala/florero.gltf')
