/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelLamparaGrande(props) {
  const { nodes, materials } = useGLTF('Sala/lamparagrande.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pSphere4.geometry} material={materials.lambert1} position={[0, 0.17, 4.36]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('Sala/lamparagrande.gltf')
