/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelLampara(props) {
  const { nodes, materials } = useGLTF('Sala/lampara.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bulb_low001.geometry} material={nodes.Bulb_low001.material} position={[4.18, 1.66, -1.55]} scale={0.11} />
      <mesh geometry={nodes.Connector_low001.geometry} material={nodes.Connector_low001.material} position={[4.18, 1.55, -1.55]} scale={0.11} />
      <mesh geometry={nodes.Shade_low001.geometry} material={materials.lambert5} position={[4.18, 1.68, -1.55]} scale={0.11} />
      <mesh geometry={nodes.Stand_low001.geometry} material={materials.lambert1} position={[4.18, 0.9, -1.55]} scale={0.11} />
    </group>
  )
}

useGLTF.preload('Sala/lampara.gltf')
