/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelLibro(props) {
  const { nodes, materials } = useGLTF('Sala/libro.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CM_Book_HR_Geometry001.geometry} material={materials['Default OBJ']} position={[-0.18, 4.47, -4.88]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={0} />
    </group>
  )
}

useGLTF.preload('Sala/libro.gltf')
