/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelMaceta(props) {
  const { nodes, materials } = useGLTF('Sala/maceta.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder002_Cylinder001.geometry} material={materials.barrederas} position={[-3.86, -0.04, 4.04]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.Cylinder006_Cylinder000.geometry} material={materials.Tierra} position={[-3.86, -0.04, 4.04]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.leaves001_leaves003.geometry} material={materials.Hojas} position={[-3.86, -0.04, 4.04]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.tree003_CUtree002.geometry} material={materials.Tallos} position={[-3.86, -0.04, 4.04]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
    </group>
  )
}

useGLTF.preload('Sala/maceta.gltf')
