/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelMesita(props) {
  const { nodes, materials } = useGLTF('Sala/mesita.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesa.geometry} material={materials.barrederas} position={[-0.1, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('Sala/mesita.gltf')
