/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelMuebles(props) {
  const { nodes, materials } = useGLTF('Sala/muebles.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane004.geometry} material={materials.Madera2} position={[-3.45, 0.28, -0.92]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials.Madera2} position={[-1.39, 0.28, -0.91]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials.Tela3} position={[-3.45, 0.28, -0.92]} scale={[1.29, 1, 3.92]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials.Tela3} position={[-3.45, 0.28, -0.92]} scale={[1.29, 1, 3.92]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials.Tela3} position={[-3.45, 0.28, -0.92]} scale={[1.29, 1, 3.92]} />
      <mesh geometry={nodes.Plane009.geometry} material={materials.Madera2} position={[-1.39, 0.28, -0.91]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials.Tela3} position={[-3.45, 0.28, -0.92]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.Tela3} position={[-3.45, 0.28, -0.92]} />
      <mesh geometry={nodes.Plane013.geometry} material={materials.Tela3} position={[-3.45, 0.28, -0.92]} />
      <mesh geometry={nodes.Plane015.geometry} material={materials.Tela3} position={[-3.45, 0.28, -0.92]} />
      <mesh geometry={nodes.Plane016.geometry} material={materials.Tela3} position={[-3.45, 0.28, -0.92]} />
      <mesh geometry={nodes.Plane017.geometry} material={materials.Tela3} position={[-3.45, 0.28, -0.92]} />
      <mesh geometry={nodes.Plane019.geometry} material={materials.Tela3} position={[-3.45, 0.28, -0.92]} />
      <mesh geometry={nodes.Plane020.geometry} material={materials.Madera2} position={[-1.39, 0.28, -5.97]} />
      <mesh geometry={nodes.Plane021.geometry} material={materials.Madera2} position={[-3.45, 0.28, -5.97]} />
      <mesh geometry={nodes.Plane022.geometry} material={materials.Madera2} position={[-3.45, 0.28, -6.46]} />
      <mesh geometry={nodes.Plane023.geometry} material={materials.Madera2} position={[-3.45, 0.28, -8.31]} />
      <mesh geometry={nodes.Plane024.geometry} material={materials.Madera2} position={[-1.42, 0.28, -8.35]} />
      <mesh geometry={nodes.Plane025.geometry} material={materials.Madera2} position={[-1.42, 0.28, -6.43]} />
      <mesh geometry={nodes.Plane026.geometry} material={materials.Madera2} position={[-0.95, 0.28, -6.43]} />
      <mesh geometry={nodes.Plane027.geometry} material={materials.Madera2} position={[2.23, 0.28, -6.43]} />
      <mesh geometry={nodes.Plane028.geometry} material={materials.Madera2} position={[2.23, 0.28, -8.36]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Tela3} position={[-3.73, 1.91, -3.73]} rotation={[0, -Math.PI / 4, 0]} scale={[0.46, 1, 1.95]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Tela3} position={[-4.1, 1.93, 1.06]} rotation={[0, 0, 0.17]} scale={[0.18, 1, 1.56]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Tela3} position={[-1.1, 1.93, -4.26]} rotation={[-0.23, -Math.PI / 2, 0]} scale={[0.18, 1, 1.28]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Tela3} position={[-4.1, 1.93, -1.65]} rotation={[0, 0, 0.17]} scale={[0.18, 1, 1.58]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Tela3} position={[0.56, 1.93, -4.26]} rotation={[-0.23, -Math.PI / 2, 0]} scale={[0.18, 1, 0.71]} />
    </group>
  )
}

useGLTF.preload('Sala/muebles.gltf')
