/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelPuerta(props) {
  const { nodes, materials } = useGLTF('Sala/puerta.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Door_.geometry} material={materials.Door_1_PBR} position={[2.76, 2.19, -4.99]} scale={1.81}>
        <mesh geometry={nodes.Door_mechanism.geometry} material={materials.Door_1_PBR} position={[-0.59, 0.02, 0.04]}>
          <mesh geometry={nodes.Handle.geometry} material={materials.Manija} position={[1.1, 0, -0.04]} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('Sala/puerta.gltf')
