/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelSalaPiso(props) {
  const { nodes, materials } = useGLTF('Sala/salapiso.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.piso.geometry} material={materials.piso} />
    </group>
  )
}

useGLTF.preload('Sala/salapiso.gltf')
