/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelTV(props) {
  const { nodes, materials } = useGLTF('Sala/tv.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TV.geometry} material={materials.Tv} position={[4.13, 1.84, 0.4]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.54} />
    </group>
  )
}

useGLTF.preload('Sala/tv.gltf')
