/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelTVStand(props) {
  const { nodes, materials } = useGLTF('Sala/tvstand.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TVstand.geometry} material={materials.barrederas} position={[4.16, 0, 0.41]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={2.5} />
    </group>
  )
}

useGLTF.preload('Sala/tvstand.gltf')
