/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelVela(props) {
  const { nodes, materials } = useGLTF('Sala/vela.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.candle_2_low005.geometry} material={materials['candle 2 low']} position={[0.33, 3.54, -4.79]} />
    </group>
  )
}

useGLTF.preload('Sala/vela.gltf')
