/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelVentanasSala(props) {
  const { nodes, materials } = useGLTF('Sala/ventanas.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ventana_base.geometry} material={materials.Vidrio} position={[-5.13, 2.5, 3.37]} rotation={[-Math.PI, 0, 0]} scale={[-1, -0.76, -0.15]} />
    </group>
  )
}

useGLTF.preload('Sala/ventanas.gltf')
